<?php

/**
 * @file
 * Contains simple_ajax_form.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_ajax_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_ajax_form module.
    case 'help.page.simple_ajax_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo of simple Ajax Form') . '</p>';
      return $output;

    default:
  }
}
